#version 460 core
#extension GL_EXT_ray_tracing : require

layout(push_constant) uniform RtxPush {
    vec3 light_direction;
    float light_radius;
    vec3 light_color;
    vec3 ambient_color;

    uint sample_factor;
    uint ray_depth;
} rtx_push;

layout(set = 0, binding = 0) uniform accelerationStructureEXT tlas;
layout(set = 0, binding = 1, rgba8) uniform image2D output_image;
layout(set = 0, binding = 2) uniform Camera {
    mat4 view;
    mat4 proj;
} camera;

struct Payload {
    vec3 color;
    vec2 image_coord;
    uint ttl;
};

layout(location = 0) rayPayloadEXT Payload payload;

vec3 gamma_correct(vec3 color) {
    return pow(color, vec3(1.0 / 2.2));
}

void main()
{
    mat4 inverse_view = inverse(camera.view);

    ivec2 pixel = ivec2(gl_LaunchIDEXT.xy);
    ivec2 image_size = ivec2(gl_LaunchSizeEXT.xy);
    vec3 origin = inverse_view[3].xyz;

    vec3 accumulated_color = vec3(0.0);

    for(uint i = 0; i < rtx_push.sample_factor; i++) {
        for(uint j = 0; j < rtx_push.sample_factor; j++) {
            vec2 in_pixel_offset = vec2(
                (float(i) + 0.5) / float(rtx_push.sample_factor),
                (float(j) + 0.5) / float(rtx_push.sample_factor)
            );

            vec2 ndc = (vec2(pixel) + in_pixel_offset) / vec2(image_size) * 2.0 - 1.0;

            vec4 target = inverse_view * camera.proj * vec4(ndc, -1.0, 0.0);
            vec3 dir = normalize(target.xyz);

            payload.color = vec3(1.0);
            payload.image_coord = ndc;
            payload.ttl = rtx_push.ray_depth;

            traceRayEXT(
                tlas,                      // acceleration structure
                gl_RayFlagsOpaqueEXT,      // ray flags
                0xFF,                      // cull mask
                0,                         // sbtRecordOffset
                0,                         // sbtRecordStride
                0,                         // missIndex
                origin,                    // ray origin
                0.0,                       // minT
                dir,                       // ray direction
                10000.0,                   // maxT
                0                          // location of payload
            );

            accumulated_color += payload.color;
        }
    }

    accumulated_color /= rtx_push.sample_factor * rtx_push.sample_factor;

    imageStore(output_image, pixel, vec4(gamma_correct(accumulated_color), 1.0));
}