#version 460 core
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require

#include "rtx_include/rtx_push.glsl"
#include "rtx_include/payload.glsl"

layout(location = 0) rayPayloadEXT PathPayload payload;

#include "rtx_include/tlas.glsl"
layout(set = 0, binding = 1, rgba8) uniform image2D output_image;
#include "rtx_include/camera.glsl"

#include "rtx_include/rand.glsl"

vec3 gamma_correct(vec3 color) {
    return pow(color, vec3(1.0 / 2.2));
}

void main()
{
    mat4 inverse_view = inverse(camera.view);

    ivec2 pixel = ivec2(gl_LaunchIDEXT.xy);
    ivec2 image_size = ivec2(gl_LaunchSizeEXT.xy);

    vec3 accumulated_color = vec3(0.0);

    for(uint i = 0; i < rtx_push.sample_factor; i++) {
        for(uint j = 0; j < rtx_push.sample_factor; j++) {
            vec2 in_pixel_offset = vec2(
                (float(i) + 0.5) / float(rtx_push.sample_factor),
                (float(j) + 0.5) / float(rtx_push.sample_factor)
            );

            vec2 ndc = (vec2(pixel) + in_pixel_offset) / vec2(image_size) * 2.0 - 1.0;
            
            vec3 local_origin = vec3(rand_circle(ndc * 2.4f) * camera.relative_lens_radius, 0.0f);
            vec3 local_target = (camera.proj * vec4(ndc, -1.0f, 1.0f)).xyz;
            vec3 local_dir = local_target - local_origin;

            vec3 origin = (inverse_view * vec4(local_origin * camera.focus_distance, 1.0f)).xyz;

            vec3 dir = normalize((inverse_view * vec4(local_dir, 0.0f)).xyz);

            // vec3 origin = (inverse_view * vec4(rand_circle(ndc * 2.4f) * camera.relative_lens_radius * camera.focus_distance, 0.0f, 1.0f)).xyz;

            // vec4 target = inverse_view * camera.proj * (vec4(ndc * camera.focus_distance, -camera.focus_distance, 1.0f));
            // vec3 dir = normalize(target.xyz - origin);

            payload.color = vec3(1.0);
            payload.image_coord = ndc;
            payload.ttl = rtx_push.ray_depth;

            traceRayEXT(
                tlas,                      // acceleration structure
                gl_RayFlagsNoneEXT,        // ray flags
                0xFF,                      // cull mask
                0,                         // sbtRecordOffset
                0,                         // sbtRecordStride
                0,                         // missIndex
                origin,                    // ray origin
                0.0,                       // minT
                dir,                       // ray direction
                10000.0,                   // maxT
                0                          // location of payload
            );

            accumulated_color += payload.color;
        }
    }

    accumulated_color /= rtx_push.sample_factor * rtx_push.sample_factor;

    imageStore(output_image, pixel, vec4(gamma_correct(accumulated_color), 1.0));
}