#version 460 core
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT tlas;
layout(set = 0, binding = 1, rgba8) uniform image2D output_image;
layout(set = 0, binding = 2) uniform Camera {
    mat4 view;
    mat4 proj;
} camera;

layout(location = 0) rayPayloadEXT vec3 payload;

void main()
{
    mat4 inverse_view = inverse(camera.view);

    ivec2 pixel = ivec2(gl_LaunchIDEXT.xy);
    ivec2 image_size = ivec2(gl_LaunchSizeEXT.xy);
    vec2 ndc = (vec2(pixel) + 0.5) / vec2(image_size) * 2.0 - 1.0;

    vec3 origin = inverse_view[3].xyz;

    vec4 target = inverse_view * camera.proj * vec4(ndc, -1.0, 0.0);
    vec3 dir = normalize(target.xyz);

    payload = vec3(0.0);

    traceRayEXT(
        tlas,                      // acceleration structure
        gl_RayFlagsOpaqueEXT,      // ray flags
        0xFF,                      // cull mask
        0,                         // sbtRecordOffset
        0,                         // sbtRecordStride
        0,                         // missIndex
        origin,                    // ray origin
        0.0,                       // minT
        dir,                       // ray direction
        10000.0,                   // maxT
        0                          // location of payload
    );

    imageStore(output_image, pixel, vec4(payload, 1.0));
}