#version 460 core
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1, rgba8) uniform image2D outputImage;

layout(location = 0) rayPayloadEXT vec3 payload;

void main()
{
    ivec2 pixel = ivec2(gl_LaunchIDEXT.xy);
    /*
    ivec2 imageSize = ivec2(gl_LaunchSizeEXT.xy);

    vec2 uv = (vec2(pixel) + 0.5) / vec2(imageSize) * 2.0 - 1.0;

    vec3 origin = vec3(0.0, 0.0, 0.0);
    vec3 dir = normalize(vec3(uv, -1.0));

    payload = vec3(0.0);

    traceRayEXT(
        topLevelAS,                // acceleration structure
        gl_RayFlagsOpaqueEXT,      // ray flags
        0xFF,                      // cull mask
        0,                         // sbtRecordOffset
        0,                         // sbtRecordStride
        0,                         // missIndex
        origin,                    // ray origin
        0.0,                       // minT
        dir,                       // ray direction
        10000.0,                   // maxT
        0                          // location of payload
    );
    */

    imageStore(outputImage, pixel, vec4(0.0, 1.0, 0.0, 1.0));
}